/**
 * 分享海报组件
 * 
 * 使用 HTML2Canvas 生成可下载的行程海报
 */

import React, { useRef, useState } from 'react';
import { Sparkles, Navigation, Download, Loader2 } from 'lucide-react';

export function PosterView({ data }) {
    const posterRef = useRef(null);
    const [isGenerating, setIsGenerating] = useState(false);

    if (!data) return <div className="text-center text-gray-500">无法获取海报数据</div>;

    const handleDownload = async () => {
        setIsGenerating(true);
        try {
            // 动态加载 html2canvas
            if (!window.html2canvas) {
                await new Promise((resolve, reject) => {
                    const script = document.createElement('script');
                    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';
                    script.onload = resolve;
                    script.onerror = reject;
                    document.head.appendChild(script);
                });
            }

            const canvas = await window.html2canvas(posterRef.current, {
                useCORS: true,
                backgroundColor: null,
                scale: 2, // 高清
            });

            const link = document.createElement('a');
            link.download = `TravelMind-${data.destination}.png`;
            link.href = canvas.toDataURL('image/png');
            link.click();
        } catch (error) {
            console.error('Poster generation failed', error);
            alert('海报生成失败，请稍后重试');
        }
        setIsGenerating(false);
    };

    return (
        <div className="flex flex-col items-center animate-fadeIn gap-4">
            {/* 海报容器 */}
            <div
                ref={posterRef}
                className="w-full max-w-sm bg-gradient-to-br from-indigo-900 to-purple-900 border border-white/20 rounded-2xl overflow-hidden shadow-2xl relative aspect-[3/4] p-6 flex flex-col"
            >
                <div className="absolute top-0 right-0 p-4 opacity-20">
                    <Sparkles size={100} className="text-white" />
                </div>
                <div className="relative z-10 flex-1 flex flex-col justify-between">
                    <div>
                        <h2 className="text-3xl font-black text-white tracking-tight mb-1">
                            {data.destination}
                        </h2>
                        <p className="text-indigo-200 text-sm uppercase tracking-widest">
                            {data.days}
                        </p>
                    </div>

                    <div className="space-y-4 my-6">
                        {data.highlights?.map((h, i) => (
                            <div key={i} className="flex items-center gap-3">
                                <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                                <span className="text-white text-lg font-light">{h}</span>
                            </div>
                        ))}
                    </div>

                    <div className="mt-auto">
                        <div className="flex items-end justify-between">
                            <div>
                                <p className="text-xs text-indigo-300 mb-1">Generated by</p>
                                <div className="flex items-center gap-1.5">
                                    <div className="bg-white p-1 rounded-md">
                                        <Navigation size={12} className="text-indigo-900" />
                                    </div>
                                    <span className="font-bold text-white">TravelMind</span>
                                </div>
                            </div>
                            <div className="text-right">
                                <p className="text-xs text-indigo-300 mb-1">Budget Est.</p>
                                <p className="text-xl font-bold text-white">{data.budget}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* 下载按钮 */}
            <button
                onClick={handleDownload}
                disabled={isGenerating}
                className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-full font-bold shadow-lg shadow-blue-600/30 transition-all hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
            >
                {isGenerating ? (
                    <Loader2 size={18} className="animate-spin" />
                ) : (
                    <Download size={18} />
                )}
                {isGenerating ? '正在渲染...' : '保存海报到相册'}
            </button>
            <p className="text-center text-xs text-gray-500">
                使用 HTML2Canvas 技术生成
            </p>
        </div>
    );
}

export default PosterView;
